# commit to be tagged for the new release
commit = "HEAD"

project_name = "tools-rust"
github_repo = "siderolabs/tools-rust"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
